version: '3'
services:
  db:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data/neo4j/conf:/conf
      - ./data/neo4j/plugins:/plugins
      - ./data/neo4j/data:/data
    env_file: env
    user: 1000:1000

  backend:
    build: backend
    depends_on:
      - db
    env_file: env
    entrypoint: ["./wait-for-it.sh", "db:7687", "--timeout=0", "--", "java", "-jar", "backend.jar"]

  apidoc:
    image: swaggerapi/swagger-ui
    depends_on:
      - backend
    environment:
      - API_URL=/api/apidoc.yaml

  redis:
    image: redis
    volumes:
      - ./data/redis:/data
    env_file: env
    user: 1000:1000
    command: redis-server --appendonly yes

  cytoscape-backend:
    build: cytoscape-backend
    environment:
      - NODE_ENV=production
    env_file: env
    depends_on:
      - backend
      - redis

  frontend:
    build: .
    volumes:
      - ./frontend/web:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - cytoscape-backend
