version: '3'
services:
  hnv-db:
    image: neo4j:4.2
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data/neo4j/conf:/conf
      - ./data/neo4j/plugins:/plugins
      - ./data/neo4j/data:/data
    env_file: env
    user: 1000:1000

  hnv-backend:
    build: backend
    depends_on:
      - hnv-db
    env_file: env
    entrypoint: ["./wait-for-it.sh", "hnv-db:7687", "--timeout=0", "--", "java", "-jar", "backend.jar"]

  hnv-apidoc:
    image: swaggerapi/swagger-ui
    depends_on:
      - hnv-backend
    environment:
      - API_URL=/api/apidoc.yaml

  hnv-redis:
    image: redis
    volumes:
      - ./data/redis:/data
    env_file: env
    user: 1000:1000
    command: redis-server --appendonly yes

  hnv-cytoscape-backend:
    build: cytoscape-backend
    environment:
      - NODE_ENV=production
    env_file: env
    depends_on:
      - hnv-backend
      - hnv-redis

  hnv-frontend:
    build: .
    volumes:
      - ./frontend/web:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - hnv-cytoscape-backend
